### ISSUE TITLE
[Group Manager] Removing self from an access control group

### ISSUE THREAD

**Issue by amclees** [leannedavid/prism-frontend#84]
The backend prevent users from removing themselves from access control groups and responds with a 400 in such cases. The frontend should hide the delete button to avoid this situation.

Currently, nothing happens when the delete button is clicked. This issue can be easily replicated by logging in as an Administrator and attempting to delete oneself from the Administrators group.

**Comment by leannedavid** [comment]
Enhancement implemented with commit cb831ff
